### ISSUE TITLE
The chosen multi-select box does not have a border radius. I cannot for the life of me figure out how to add it.

### ISSUE THREAD

**Issue by EminenceHC** [tsechingho/chosen-rails#45]

**Comment by denispeplin** [comment]
Surprisingly, the issue is still actual.

I'm using this CSS:

```css
.chosen-container-multi {
  margin-left: 4px;
  border-radius: 5px; // doesn't work
}
```

I've got margin, but no border-radius. Assigning this in Chrome Dev Tools also has no effect.

Rails 4.2.4, latest chosen-rails, bootstrap-sass.
